apiVersion: argoproj.io/v1alpha1
kind: Workflow                  # new type of k8s spec
metadata:
  generateName: hello-world-    # name of the workflow spec
  namespace: testground
spec:
  entrypoint: whalesay          # invoke the whalesay template
  templates:
    - name: whalesay              # name of the template
      container:
        image: docker/whalesay
        command: [ "/bin/sh" ]
        # https://stackoverflow.com/questions/40926789/create-a-file-of-a-specific-size-with-random-printable-strings-in-bash
        args: [ "-c", "dd if=/dev/urandom bs=786438 count=100 | base64" ]
        resources: # limit the resources
          limits:
            memory: 32Mi
            cpu: 100m
